name: Shippy
version: 1.0
main: com.clamzo.shippy.ShippyPlugin
api-version: 1.21
description: A plugin that allows players to build custom ships and pilot them
commands:
  givePort:
    description: Gives the player a port
    usage: /giveport
  giveShipyard:
    description: Gives the player a shipyard
    usage: /giveshipyard
  shipdebug:
    description: Your description
    usage: /shipdebug